In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [ ]:
df = pd.read_csv("data.csv")
X = df[['D_length', "D_weight"]]
y = df['y']
X.shape, y.shape

((49, 2), (49,))

In [ ]:
s = StandardScaler().fit(X)
s_X = s.transform(X)

In [ ]:
train_x, test_x, train_y, test_y = train_test_split(s_X, y, random_state = 1, test_size = 0.3)

In [ ]:
train_x.shape, test_x.shape, train_y.shape, test_y.shape

((34, 2), (15, 2), (34,), (15,))

In [ ]:
m = LogisticRegression()
m.fit(train_x, train_y)

LogisticRegression()

In [ ]:
m.score(train_x, train_y), m.score(test_x, test_y)

(1.0, 1.0)

In [ ]:
m.coef_, m.intercept_

(array([[-1.73618958, -1.26804725]]), array([-2.3556859]))

In [ ]:
from sklearn.metrics import f1_score, accuracy_score, precision_score, recall_score

In [ ]:
py = m.predict(test_x)

In [ ]:
f1_score(test_y, py)

1.0

In [ ]:
print(f"""정확도 : {accuracy_score(test_y, py)}
정밀도 : {precision_score(test_y, py)}
민감도 : {recall_score(test_y, py)}
f1점수 : {f1_score(test_y, py)}""")

정확도 : 1.0
정밀도 : 1.0
민감도 : 1.0
f1점수 : 1.0

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(test_y, py))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00         6

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15

In [ ]:
m.decision_function(test_x)

array([-4.93981229, -6.71753987,  2.05688104,  1.36665938, -1.85261398,
       -2.37056395,  1.95373466, -6.22771801,  1.83731347, -6.1722594 ,
       -6.30891186,  2.09152346, -4.48406614,  2.30874843, -4.26178372])

In [ ]:
m.classes_[m.predict(test_x)]

array([0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0])

Q1 타이타닉 데이터를 이용하여 이진 분류기를 설계 하시오

In [ ]:
import seaborn as sns
df = sns.load_dataset("titanic")
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [ ]:
df1 = df.iloc[:,:8]
df1

     survived  pclass     sex   age  sibsp  parch     fare embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [ ]:
c_d = df1[['pclass', 'sex', 'sibsp', 'parch', 'embarked']]
c_d

     pclass     sex  sibsp  parch embarked
0         3    male      1      0        S
1         1  female      1      0        C
2         3  female      0      0        S
3         1  female      1      0        S
4         3    male      0      0        S
..      ...     ...    ...    ...      ...
886       2    male      0      0        S
887       1  female      0      0        S
888       3  female      1      2        S
889       1    male      0      0        C
890       3    male      0      0        Q

[891 rows x 5 columns]

In [ ]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
ohe.fit(c_d)

OneHotEncoder()

In [ ]:
x = ohe.transform(c_d)
x.toarray()

array([[0., 0., 1., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 1., 0.],
       ...,
       [0., 0., 1., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.]])

In [ ]:
ohe.feature_names_in_

array(['pclass', 'sex', 'sibsp', 'parch', 'embarked'], dtype=object)

In [ ]:
ohe.categories_

[array([1, 2, 3]),
 array(['female', 'male'], dtype=object),
 array([0, 1, 2, 3, 4, 5, 8]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array(['C', 'Q', 'S', nan], dtype=object)]

In [ ]:
l =[]
for i in range(len(ohe.feature_names_in_)):
    l += [ohe.feature_names_in_[i] + "_" + str(결합문자) for 결합문자 in ohe.categories_[i]]
l

['pclass_1',
 'pclass_2',
 'pclass_3',
 'sex_female',
 'sex_male',
 'sibsp_0',
 'sibsp_1',
 'sibsp_2',
 'sibsp_3',
 'sibsp_4',
 'sibsp_5',
 'sibsp_8',
 'parch_0',
 'parch_1',
 'parch_2',
 'parch_3',
 'parch_4',
 'parch_5',
 'parch_6',
 'embarked_C',
 'embarked_Q',
 'embarked_S',
 'embarked_nan']

In [ ]:
ohe.get_feature_names_out()

array(['pclass_1', 'pclass_2', 'pclass_3', 'sex_female', 'sex_male',
       'sibsp_0', 'sibsp_1', 'sibsp_2', 'sibsp_3', 'sibsp_4', 'sibsp_5',
       'sibsp_8', 'parch_0', 'parch_1', 'parch_2', 'parch_3', 'parch_4',
       'parch_5', 'parch_6', 'embarked_C', 'embarked_Q', 'embarked_S',
       'embarked_nan'], dtype=object)

In [ ]:
ohe.categories_[1]

array(['female', 'male'], dtype=object)

In [ ]:
df2 = df1.drop(ohe.feature_names_in_, axis = 1)

In [ ]:
in_x = x.toarray()
ohe_df = pd.DataFrame(in_x, columns = ohe.get_feature_names_out())
ohe_df
# end_df = pd.concat([df2, ohe.df])
# end_df

,pclass_1,pclass_2,pclass_3,sex_female,sex_male,sibsp_0,sibsp_1,sibsp_2,sibsp_3,sibsp_4,...,parch_1,parch_2,parch_3,parch_4,parch_5,parch_6,embarked_C,embarked_Q,embarked_S,embarked_nan
0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
887,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
888,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
889,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
890,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [ ]:
df1_1 = df1.drop(ohe.feature_names_in_, axis = 1)
df1_1

     survived   age     fare
0           0  22.0   7.2500
1           1  38.0  71.2833
2           1  26.0   7.9250
3           1  35.0  53.1000
4           0  35.0   8.0500
..        ...   ...      ...
886         0  27.0  13.0000
887         1  19.0  30.0000
888         0   NaN  23.4500
889         1  26.0  30.0000
890         0  32.0   7.7500

[891 rows x 3 columns]

In [ ]:
end_load_df = pd.concat([df1_1, ohe_df], axis = 1)
end_load_df

,survived,age,fare,pclass_1,pclass_2,pclass_3,sex_female,sex_male,sibsp_0,sibsp_1,...,parch_1,parch_2,parch_3,parch_4,parch_5,parch_6,embarked_C,embarked_Q,embarked_S,embarked_nan
0,0,22.0,7.2500,0.0,0.0,1.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,38.0,71.2833,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,1,26.0,7.9250,0.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,35.0,53.1000,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0,35.0,8.0500,0.0,0.0,1.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,27.0,13.0000,0.0,1.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
887,1,19.0,30.0000,1.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
888,0,NaN,23.4500,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
889,1,26.0,30.0000,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
890,0,32.0,7.7500,0.0,0.0,1.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

Q1 타이타닉 데이터를 이용하여 이진 분류기를 설계 하시오

1. 데이터 수집

In [ ]:
import seaborn as sns
df=sns.load_dataset('titanic')
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

2. 데이터 전처리
 1. 결측치 처리
 2. 이상치 처리

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

-int64형 칼럼
1. PassengerId: 탑승자 데이터 일련번호
2. Survived: 생존 여부 (0=사망, 1=생존)
3. Pclass: 티켓의 선실 등급 (1=일등석, 2=이등석, 3=삼등석)
4. SibSp: 같이 탑승한 형제자매 또는 배우자 인원수
5. Parch: 같이 탑승한 부모님 또는 어린이 인원수
-float64형 칼럼
1. Age: 탑승자 나이
2. Fare: 요금
-object(문자열)형 칼럼
1. Name: 탑승자 이름
2. Sex: 탑승자 성별
3. Ticket: 티켓 번호
4. Cabin: 선실 번호
5. Embarked: 중간 정착 항구 (C=Cherbourg, Q=Queenstown, S=Southampton)

In [ ]:
# 결측치 처리
df.drop(['deck'], axis = 1, inplace = True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  embark_town  889 non-null    object
 12  alive        891 non-null    object
 13  alone        891 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(4), object(5)
memory usage: 79.4+ KB

In [ ]:
# age 결측치 평균치로 처리 & 결측치 버리기
df['age'] = df['age'].fillna(df.groupby('sex')['age'].transform('mean'))
df.dropna(subset = ['embark_town', 'embarked'], inplace = True)
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     889 non-null    int64
 1   pclass       889 non-null    int64
 2   sex          889 non-null    object
 3   age          889 non-null    float64
 4   sibsp        889 non-null    int64
 5   parch        889 non-null    int64
 6   fare         889 non-null    float64
 7   embarked     889 non-null    object
 8   class        889 non-null    category
 9   who          889 non-null    object
 10  adult_male   889 non-null    bool
 11  embark_town  889 non-null    object
 12  alive        889 non-null    object
 13  alone        889 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(4), object(5)
memory usage: 86.1+ KB

In [ ]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,Southampton,no,True
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,Southampton,yes,True
888,0,3,female,27.915709,1,2,23.4500,S,Third,woman,False,Southampton,no,False
889,1,1,male,26.000000,0,0,30.0000,C,First,man,True,Cherbourg,yes,True
890,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,Queenstown,no,True

In [ ]:
# 중복느낌인 피처 제거
df = df.drop(['class', 'who', 'adult_male', 'embark_town', 'alive'], axis = 1)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  889 non-null    int64
 1   pclass    889 non-null    int64
 2   sex       889 non-null    object
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64
 5   parch     889 non-null    int64
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object
 8   alone     889 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 95.7+ KB

In [ ]:
df['alone']

0      False
1      False
2       True
3      False
4       True
       ...
886     True
887     True
888    False
889     True
890     True
Name: alone, Length: 889, dtype: bool

In [ ]:
sc_df = df[['pclass', 'age', 'sibsp', 'parch', 'fare']]
ca_df = df[['sex', 'embarked', 'alone']]
y = df['survived']

3. 범주형처리

In [ ]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
ohe.fit(ca_df)

OneHotEncoder()

In [ ]:
ohe.feature_names_in_

array(['sex', 'embarked', 'alone'], dtype=object)

In [ ]:
ohe.categories_

[array(['female', 'male'], dtype=object),
 array(['C', 'Q', 'S'], dtype=object),
 array([False,  True])]

In [ ]:
ohe_ca_df = ohe.transform(ca_df)
ohe_ca_df.toarray().shape

(889, 7)

In [ ]:
ohe_df = pd.DataFrame(ohe_ca_df.toarray(), columns = ohe.get_feature_names_out())
ohe_df

,sex_female,sex_male,embarked_C,embarked_Q,embarked_S,alone_False,alone_True
0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
1,1.0,0.0,1.0,0.0,0.0,1.0,0.0
2,1.0,0.0,0.0,0.0,1.0,0.0,1.0
3,1.0,0.0,0.0,0.0,1.0,1.0,0.0
4,0.0,1.0,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...
884,0.0,1.0,0.0,0.0,1.0,0.0,1.0
885,1.0,0.0,0.0,0.0,1.0,0.0,1.0
886,1.0,0.0,0.0,0.0,1.0,1.0,0.0
887,0.0,1.0,1.0,0.0,0.0,0.0,1.0
888,0.0,1.0,0.0,1.0,0.0,0.0,1.0

4. 범위처리

In [ ]:
from sklearn.preprocessing import MinMaxScaler
s = MinMaxScaler().fit(sc_df)
ss_df = s.transform(sc_df)
s_df = pd.DataFrame(ss_df, columns = sc_df.columns)
s_df

     pclass       age  sibsp     parch      fare
0       1.0  0.271174  0.125  0.000000  0.014151
1       0.0  0.472229  0.125  0.000000  0.139136
2       1.0  0.321438  0.000  0.000000  0.015469
3       0.0  0.434531  0.125  0.000000  0.103644
4       1.0  0.434531  0.000  0.000000  0.015713
..      ...       ...    ...       ...       ...
884     0.5  0.334004  0.000  0.000000  0.025374
885     0.0  0.233476  0.000  0.000000  0.058556
886     1.0  0.345510  0.125  0.333333  0.045771
887     0.0  0.321438  0.000  0.000000  0.058556
888     1.0  0.396833  0.000  0.000000  0.015127

[889 rows x 5 columns]

5. 전처리된 데이터 데이터 프레임 화

In [ ]:
end_df = pd.concat([ohe_df, s_df], axis = 1)
end_df

,sex_female,sex_male,embarked_C,embarked_Q,embarked_S,alone_False,alone_True,pclass,age,sibsp,parch,fare
0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.271174,0.125,0.000000,0.014151
1,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.472229,0.125,0.000000,0.139136
2,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.321438,0.000,0.000000,0.015469
3,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.434531,0.125,0.000000,0.103644
4,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.434531,0.000,0.000000,0.015713
...,...,...,...,...,...,...,...,...,...,...,...,...
884,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.5,0.334004,0.000,0.000000,0.025374
885,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.233476,0.000,0.000000,0.058556
886,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.345510,0.125,0.333333,0.045771
887,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.321438,0.000,0.000000,0.058556
888,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.396833,0.000,0.000000,0.015127

3.학습

In [ ]:
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(end_df, y, random_state= 1, test_size = 0.3)
train_x.shape, test_x.shape, train_y.shape, test_y.shape

((622, 12), (267, 12), (622,), (267,))

In [ ]:
from sklearn.tree import DecisionTreeClassifier
m = DecisionTreeClassifier()
m.fit(train_x, train_y)

DecisionTreeClassifier()

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn_cm = KNeighborsClassifier().fit(train_x, train_y)

4.테스트 및 검증

In [ ]:
m.score(train_x, train_y), m.score(test_x, test_y)

(0.9871382636655949, 0.7677902621722846)

In [ ]:
knn_cm.score(train_x, train_y), knn_cm.score(test_x, test_y)

(0.842443729903537, 0.797752808988764)